### ISSUE TITLE
Availability selector mobile style

### ISSUE THREAD

**Issue by elimelt** [swecc-uw/swecc-client#3]
Need to add some margin or padding to the TimeSelector component in mobile view. Right now it is being cut off on iphone SE. 

<img width="446" alt="Screenshot 2024-04-01 at 7 26 10 PM" src="https://github.com/swecc-uw/pairing-client/assets/98496503/24839f15-b645-483c-87d3-1bdd0fa699ec">

**Comment by ShawnCollinge** [comment]
@elimelt is this done with your new version?

**Comment by elimelt** [comment]
Yep, completely different design for mobile now. Also I just realized when I went crazy and did a whole protocol for scheduling and committing to a time, I also added a start and stop time for the selector. I should integrate those changes soon since it's a little silly to show from like 11pm-6am by default
