### ISSUE TITLE
Off by 1 error on date.

### ISSUE THREAD

**Issue by ShawnCollinge** [swecc-uw/swecc-client#60]
When I select March 21st as my graduation date it shows up on my profile as March 20th.

<img width="227" alt="image" src="https://github.com/user-attachments/assets/e937351b-f687-413e-b0b0-2ab13aebdcf1">

**Comment by elimelt** [comment]
> When I select March 21st as my graduation date it shows up on my profile as March 20th.
> 
> 
> 
> <img width="227" alt="image" src="https://github.com/user-attachments/assets/e937351b-f687-413e-b0b0-2ab13aebdcf1">
> 
> 

i wonder if this is caused by time zone issue, or if i just messed up presentation. will check tn
