### ISSUE TITLE
Like When2Meet, be able to select multiple time options when you drag your mouse

### ISSUE THREAD

**Issue by mathlord2** [swecc-uw/swecc-client#7]
See the recording below for what I mean. Notice how dragging over multiple timeslots doesn't work and simply highlights them blue. Currently, you can only click on individual times, which can be tedious.

https://github.com/swecc-uw/pairing-client/assets/42785168/d4639150-b0cd-4402-9eb6-345bc64b7c92

**Comment by ShawnCollinge** [comment]
@elimelt I think this is done no?
