### ISSUE TITLE
Footer is irrelevant to swecc. 

### ISSUE THREAD

**Issue by ShawnCollinge** [swecc-uw/swecc-client#74]
None of the links work and they aren't really relevant. 

<img width="1375" alt="image" src="https://github.com/user-attachments/assets/b26de1ca-04a5-4772-be47-fdc39abcf184">

**Comment by elimelt** [comment]
wdym bro we need all this stuff

**Comment by ShawnCollinge** [comment]
All the links are dead, provide the content then for all the footer links or remove them.
